# Generated by Django 5.1.5 on 2025-01-25 23:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventario', '0001_initial'),
        ('pedidos', '0001_initial'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pedidos', to='usuarios.cliente'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='sucursal_destino',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pedidos_destino', to='inventario.sucursal'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='sucursal_origen',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pedidos_origen', to='inventario.sucursal'),
        ),
        migrations.AddField(
            model_name='pedidoproducto',
            name='pedido',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pedidos.pedido'),
        ),
        migrations.AddField(
            model_name='pedidoproducto',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.producto'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='productos',
            field=models.ManyToManyField(through='pedidos.PedidoProducto', to='inventario.producto'),
        ),
    ]
